name: update data

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  my-job:
    name: Update kanagawa data
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run 
      run: |
        python main.py
    - name: commit
      run: |
        git config --global user.name "[BOT]tamitami"
        git config --global user.email "68597117+tamitami5c@users.noreply.github.com"
        git add hospital_beds_data.json
        git commit -m "[BOT]データ更新" || true
        git push origin main || true
